name: Playwright Tests
on:
  push:
    branches: [ main, master,Devops ]
  pull_request:
    branches: [ main, master,Devops ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies and Playwright
      run: |
        yarn install  # Install project dependencies
        yarn install --production=false  # Install devDependencies, including Playwright
      working-directory: ./Client    
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: ./Client
    - name: Run Playwright tests
      run: yarn playwright test
      working-directory: ./Client
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
